repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        exclude: ^(examples/harbor/hello-world/|examples/supercon-extraction/alias_matching/|examples/tc-precedent-search/)
      # Run the formatter.
      - id: ruff-format